import React from 'react';

export const Terms = () => {
  return (
    <div style={{ fontFamily: 'Georgia, serif', maxWidth: 720, margin: '0 auto', padding: '48px 24px', color: '#1A1A1A', lineHeight: 1.75 }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 4 }}>Terms of Service</h1>
      <p style={{ color: '#888', fontSize: 14, marginBottom: 40 }}>Last updated: May 2025</p>

      <p>By accessing or using StudyIndex ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>1. Use of the App</h2>
      <p>StudyIndex is an AI-powered study planner. You may use it for personal, non-commercial study and educational purposes. You agree not to:</p>
      <ul style={{ paddingLeft: 24 }}>
        <li>Upload content you do not have the right to share</li>
        <li>Attempt to reverse-engineer or exploit the App</li>
        <li>Use the App for any unlawful purpose</li>
        <li>Upload content that is harmful, offensive, or violates any third-party rights</li>
      </ul>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>2. Account</h2>
      <p>You must sign in with a valid Google account to use certain features. You are responsible for maintaining the security of your account. We are not liable for any loss resulting from unauthorised access to your account.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>3. Uploaded Content</h2>
      <p>You retain ownership of any documents or files you upload. By uploading content, you grant us a limited, temporary licence to process it solely for the purpose of generating your study plan. We do not claim ownership of your content.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>4. AI-Generated Content</h2>
      <p>Study plans, flashcards, and summaries are generated by AI and may contain errors or inaccuracies. StudyIndex is a study aid — always verify important information with authoritative sources. We are not responsible for outcomes resulting from reliance on AI-generated content.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>5. Intellectual Property</h2>
      <p>The StudyIndex name, logo, and App interface are our intellectual property. You may not reproduce or distribute them without permission.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>6. Disclaimers</h2>
      <p>The App is provided "as is" without warranties of any kind. We do not guarantee that the App will be uninterrupted, error-free, or that AI-generated content will be accurate or complete.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>7. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, StudyIndex shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>8. Termination</h2>
      <p>We reserve the right to suspend or terminate access to the App for any user who violates these Terms.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>9. Changes to Terms</h2>
      <p>We may update these Terms at any time. Continued use of the App after changes constitutes acceptance. We will indicate the date of the latest revision at the top of this page.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>10. Governing Law</h2>
      <p>These Terms are governed by applicable law. Any disputes shall be resolved in the appropriate courts of jurisdiction.</p>

      <h2 style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>11. Contact</h2>
      <p>For questions about these Terms, email: <a href="mailto:support@studyindex.app" style={{ color: '#5A5A40' }}>support@studyindex.app</a></p>

      <p style={{ marginTop: 48, color: '#aaa', fontSize: 13 }}>© 2025 StudyIndex. All rights reserved.</p>
    </div>
  );
};
